### PR TITLE
updated dependencies. most significantly, moved to latest `ssb-server`

### PR DESCRIPTION
**Pull request by austinfrey**
While doing my village issue tracker assigment, I noticed that this repo, [ssb-testing-guide](https://github.com/ssbc/ssb-testing-guide/), makes use of this module quite a bit, so i wanted to make sure the deps were up to date.

all tests still pass.

### CODE REVIEW

**Comment by austinfrey** [comment]
I'm not sure this is relevant anymore, it seems easy enough to create testbots with regular `ssb-server` by passing a `temp` config option. should this repo be archived instead?

**Comment by arj03** [comment]
@austinfrey it is relevant. I will review it over the next few days. I still use this library.

**Comment by arj03** [comment]
Tested and works. Thanks @austinfrey :)

**Comment by austinfrey** [comment]
cool, Thanks @arj03 !

**Pull request merged**
