### PR TITLE
Enable db2 usage

### PR DESCRIPTION
**Pull request by arj03**
This enables db2 usage

### CODE REVIEW

**Review by mixmix — APPROVED** [review]
Yes, AND I think perhaps you should add an opts.db1

For the instances you want to have both installed (does such a thing exist?)

**Comment by mixmix** [comment]
🍍

**Comment by arj03** [comment]
It does make sense, but normally only in a migrate situation. And in any case you can always enable db1 as a plugin. The main reason I don't like a db1 flag is that that would be true by default, so to enable only db2 you have to do `{ db2: true, db1: false }` which is a bit of a gotcha.

**Comment by arj03** [comment]
Also this PR came about because I was looking at adding db2 support in CRUT

**Comment by mixmix** [comment]
Yeah go for it, merge those i reckon

**Comment by arj03** [comment]
Thanks for the 🍍

**Comment by mixmix** [comment]
Woop!

**Pull request merged**
