### PR TITLE
Add noUse opt

### PR DESCRIPTION
**Pull request by Powersource**
For https://github.com/ssbc/ssb-tribes/issues/98

### CODE REVIEW

**Comment by Powersource** [comment]
tests "failing" but it's only the licenses and that's old i guess

**Review by mixmix — CHANGES_REQUESTED** [review]
Love this addition. For me `noUse` suggests that the `sbot.use` function will be disabled?

Other ideas which could be clearer:
- `noDb: true`
- `db: dbPlugin`  for custom db module , or `db: false` to have none

**Comment by Powersource** [comment]
renamed it to `noDefaultUse`

**Review by mixmix — APPROVED** [review]

**Comment by Powersource** [comment]
v2.2.0

**Pull request merged**
